"""Onboarding guide models."""

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any

from pydantic import BaseModel, Field


class SectionType(str, Enum):
    """Type of guide section."""
    
    OVERVIEW = "overview"
    ARCHITECTURE = "architecture"
    MODULES = "modules"
    SETUP = "setup"
    START_HERE = "start_here"
    DEPENDENCIES = "dependencies"
    CUSTOM = "custom"


class Section(BaseModel):
    """
    A section of the onboarding guide.
    
    Sections can be nested via subsections.
    """
    
    section_type: SectionType = Field(description="Type of section")
    title: str = Field(description="Section title")
    content: str = Field(default="", description="Section content (Markdown)")
    subsections: list[Section] = Field(default_factory=list, description="Nested sections")
    metadata: dict[str, Any] = Field(default_factory=dict, description="Additional metadata")
    
    model_config = {"frozen": False}


class OnboardingGuide(BaseModel):
    """
    Generated onboarding document for a project.
    
    Contains structured sections that can be rendered to various formats.
    """
    
    project_name: str = Field(description="Name of the analyzed project")
    project_path: str = Field(description="Path to the analyzed project")
    generated_at: datetime = Field(default_factory=datetime.now)
    sections: list[Section] = Field(default_factory=list)
    
    # Generation metadata
    model_used: str | None = Field(default=None, description="LLM model used for summaries")
    generation_time_seconds: float | None = Field(default=None)
    cache_hits: int = Field(default=0)
    cache_misses: int = Field(default=0)
    
    model_config = {"frozen": False}
    
    def add_section(self, section: Section) -> None:
        """Add a section to the guide."""
        self.sections.append(section)
    
    def get_section(self, section_type: SectionType) -> Section | None:
        """Get a section by type."""
        for section in self.sections:
            if section.section_type == section_type:
                return section
        return None
    
    def to_markdown(self) -> str:
        """
        Render the guide as Markdown.
        
        Returns:
            Complete Markdown document
        """
        lines = [
            f"# {self.project_name} — Onboarding Guide",
            "",
            f"> Generated: {self.generated_at.strftime('%Y-%m-%d %H:%M')}",
            "",
            "---",
            "",
        ]
        
        # Table of contents
        lines.append("## Table of Contents")
        lines.append("")
        for i, section in enumerate(self.sections, 1):
            anchor = section.title.lower().replace(" ", "-")
            lines.append(f"{i}. [{section.title}](#{anchor})")
        lines.append("")
        lines.append("---")
        lines.append("")
        
        # Sections
        for section in self.sections:
            lines.extend(self._render_section(section, level=2))
        
        # Footer
        lines.append("---")
        lines.append("")
        lines.append("*Generated by [DevWayfinder](https://github.com/IMAGINARY9/DevWayfinder)*")
        
        return "\n".join(lines)
    
    def _render_section(self, section: Section, level: int) -> list[str]:
        """Render a section and its subsections."""
        lines = []
        
        # Header
        prefix = "#" * level
        lines.append(f"{prefix} {section.title}")
        lines.append("")
        
        # Content
        if section.content:
            lines.append(section.content)
            lines.append("")
        
        # Subsections
        for subsection in section.subsections:
            lines.extend(self._render_section(subsection, level + 1))
        
        return lines
